id: PAFE6BFF8
initial_creation_type: ocr
source_metadata:
  volumes:
    487944284b60438c88fe62c894c15a13:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: དེ་ཁོ་ན་ཉིད་སྒྲོན་མ།
      total_pages: 1853
      volume_number: 25
